# Generated by Django 2.0.7 on 2018-08-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companycategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=30)),
                ('category_description', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
