# Generated by Django 2.0.7 on 2018-08-23 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyregisteration', '0002_companyreg'),
        ('productcategory', '0002_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=30)),
                ('product_rate', models.CharField(default='', max_length=30)),
                ('product_description', models.CharField(default='', max_length=500)),
                ('product_image', models.ImageField(upload_to='bestshoppi')),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyregisteration.CompanyReg')),
                ('productcat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productcategory.ProductCategory')),
            ],
        ),
    ]
