# Generated by Django 2.0.7 on 2018-08-23 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('district', '0001_initial'),
        ('subscriptioncategory', '0002_subscriptioncategory'),
        ('companycategory', '0002_companycategory'),
        ('companyregisteration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(default='', max_length=30)),
                ('email_id', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=100)),
                ('licence_proof', models.CharField(default='', max_length=20)),
                ('comp_decsription', models.CharField(default='', max_length=500)),
                ('comp_image', models.ImageField(upload_to='bestshoppi')),
                ('status', models.IntegerField()),
                ('username', models.CharField(default='', max_length=15)),
                ('password', models.CharField(default='', max_length=15)),
                ('companycat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companycategory.CompanyCategory')),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='district.District')),
                ('subscriptioncat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptioncategory.SubscriptionCategory')),
            ],
        ),
    ]
