# Generated by Django 2.0.7 on 2018-08-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyregisteration', '0002_companyreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyreg',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
