# Generated by Django 2.0.7 on 2018-08-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyregisteration', '0003_auto_20180831_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyreg',
            name='status',
            field=models.BigIntegerField(default=0),
        ),
    ]
