# Generated by Django 2.0.7 on 2018-08-31 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyregisteration', '0004_auto_20180831_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyreg',
            name='companycat_id',
        ),
        migrations.RemoveField(
            model_name='companyreg',
            name='subscriptioncat_id',
        ),
    ]
