# Generated by Django 2.0.7 on 2018-08-31 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyregisteration', '0005_auto_20180831_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyreg',
            name='district_id',
        ),
    ]
