# Generated by Django 2.0.7 on 2018-08-31 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyregisteration', '0007_remove_companyreg_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyreg',
            name='address',
        ),
        migrations.RemoveField(
            model_name='companyreg',
            name='comp_decsription',
        ),
        migrations.RemoveField(
            model_name='companyreg',
            name='comp_image',
        ),
        migrations.RemoveField(
            model_name='companyreg',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='companyreg',
            name='licence_proof',
        ),
        migrations.RemoveField(
            model_name='companyreg',
            name='password',
        ),
        migrations.RemoveField(
            model_name='companyreg',
            name='username',
        ),
    ]
