# Generated by Django 2.0.7 on 2018-08-31 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
        ('companyregisteration', '0008_auto_20180831_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreg',
            name='district_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='district.District'),
            preserve_default=False,
        ),
    ]
