# Generated by Django 2.0.7 on 2018-08-31 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companycategory', '0002_companycategory'),
        ('companyregisteration', '0009_companyreg_district_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreg',
            name='companycat_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companycategory.CompanyCategory'),
            preserve_default=False,
        ),
    ]
