# Generated by Django 2.0.7 on 2018-08-31 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptioncategory', '0002_subscriptioncategory'),
        ('companyregisteration', '0010_companyreg_companycat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreg',
            name='subscriptioncat_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subscriptioncategory.SubscriptionCategory'),
            preserve_default=False,
        ),
    ]
