# Generated by Django 2.0.7 on 2018-08-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyregisteration', '0011_companyreg_subscriptioncat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreg',
            name='comp_image',
            field=models.ImageField(default=1, upload_to='bestshoppi'),
            preserve_default=False,
        ),
    ]
