# Generated by Django 2.0.7 on 2018-08-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyregisteration', '0012_companyreg_comp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreg',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='companyreg',
            name='comp_decsription',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='companyreg',
            name='email_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='companyreg',
            name='licence_proof',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='companyreg',
            name='password',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='companyreg',
            name='status',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyreg',
            name='username',
            field=models.CharField(default='', max_length=15),
        ),
    ]
