# Generated by Django 2.0.7 on 2018-08-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyregisteration', '0014_auto_20180831_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreg',
            name='email_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
