# Generated by Django 2.0.7 on 2018-08-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyregisteration', '0015_companyreg_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreg',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='companyreg',
            name='licence_proof',
            field=models.CharField(default='', max_length=20),
        ),
    ]
