# Generated by Django 2.0.7 on 2018-08-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyregisteration', '0016_auto_20180831_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreg',
            name='comp_decsription',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='companyreg',
            name='password',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='companyreg',
            name='username',
            field=models.CharField(default='', max_length=15),
        ),
    ]
