# Generated by Django 2.0.7 on 2018-08-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyregisteration', '0017_auto_20180831_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreg',
            name='status',
            field=models.BigIntegerField(default='0'),
        ),
    ]
