# Generated by Django 2.0.7 on 2018-10-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyregisteration', '0018_companyreg_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyreg',
            name='email_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
