# Generated by Django 2.0.7 on 2018-11-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_purchase_productname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='total',
            field=models.BigIntegerField(),
        ),
    ]
