# Generated by Django 2.0.7 on 2018-11-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20181109_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='Custid',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
