# Generated by Django 2.0.7 on 2018-11-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_purchase_custid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='Custid',
            field=models.CharField(max_length=10),
        ),
    ]
