# Generated by Django 2.0.7 on 2018-11-09 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_auto_20181109_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
