# Generated by Django 2.0.7 on 2018-11-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_purchase_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='orderno',
            field=models.CharField(default='101', max_length=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
