# Generated by Django 2.0.7 on 2018-08-22 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custregisteration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('gender', models.CharField(default='', max_length=10)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('email', models.CharField(default='', max_length=30)),
                ('contactno', models.CharField(default='', max_length=30)),
                ('username', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
