# Generated by Django 2.0.7 on 2018-09-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custregisteration', '0002_customerreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreg',
            name='confirm',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customerreg',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
